import {useEffect,useState} from 'react';
import type {QuestionResult,Worksheet as Sheet} from '../types';
import {symbol} from '../generators/questions';
import {duration} from '../services/progress';
export function Worksheet({sheet,name,visibleTimer,onChange,onComplete,onExit}:{sheet:Sheet;name:string;visibleTimer:boolean;onChange:(s:Sheet)=>void;onComplete:(s:Sheet)=>void;onExit:()=>void}){
 const [answer,setAnswer]=useState('');const [feedback,setFeedback]=useState('');const [now,setNow]=useState(Date.now());
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);
 const index=sheet.results.length,q=sheet.questions[index];
 function submit(){if(answer.trim()===''||!/^\d+$/.test(answer)){setFeedback('Type a whole number first.');return;}const n=Number(answer);const attempts=sheet.attempts+1;const ok=n===q.answer;onChange({...sheet,attempts,firstAnswer:sheet.firstAnswer??n,correct:ok});setFeedback(ok?'Correct! Nicely done.':'Try again. You can do this.');if(!ok)setAnswer('');}
 function next(){const end=Date.now();const result:QuestionResult={question:q,firstAnswer:sheet.firstAnswer!,attempts:sheet.attempts,firstCorrect:sheet.attempts===1,questionStartTime:sheet.questionStartTime,questionEndTime:end,timeSpent:(end-sheet.questionStartTime)/1000};const updated={...sheet,results:[...sheet.results,result],attempts:0,firstAnswer:null,correct:false,questionStartTime:end};setAnswer('');setFeedback('');if(updated.results.length===sheet.questions.length)onComplete(updated);else onChange(updated);}
 return <><div className="section-head"><div><span className="eyebrow">{name}'S PRACTICE</span><h1>{sheet.mode==='mixed'?'Mixed':sheet.mode==='addition'?'Addition':'Subtraction'} worksheet</h1></div><button className="quiet" onClick={onExit}>Save & exit</button></div><div className="sheet-top"><span>Question {index+1} of {sheet.questions.length}</span>{visibleTimer&&<span aria-label="Elapsed worksheet time">◷ {duration((now-sheet.startedAt)/1000)}</span>}</div><div className="progress"><i style={{width:`${index/sheet.questions.length*100}%`}}/></div><section className="question-panel"><p className="muted">Take your time. One step at a time.</p><form onSubmit={e=>{e.preventDefault();sheet.correct?next():submit();}}><div className="equation">{q.a} <span>{symbol(q.skill)}</span> {q.b} <span>=</span></div><label className="answer-label">Your answer<input key={q.id} type="text" inputMode="numeric" autoComplete="off" value={answer} onChange={e=>setAnswer(e.target.value)} disabled={sheet.correct} autoFocus aria-label="Your answer"/></label><div className={`feedback ${sheet.correct?'success':''}`} role="status">{sheet.correct?'✓ ':''}{feedback|| (sheet.correct?'Correct! Nicely done.':'')}</div><button className="primary">{sheet.correct?index+1===sheet.questions.length?'Finish worksheet':'Next question':'Check answer'}</button></form></section></>;
}
